TOPDIR := $(realpath ..)

all: dtb test modules

DTS_SRC  = rv32.dts
MOD_SRC  = si7210_driver.c
TEST_SRC = test_app.c

include ${TOPDIR}/build_mkfiles/config.mk
include ${TOPDIR}/build_mkfiles/common.mk
